version: '4.1'

services:
    user-service:
        ports:
            - "3001:80"
        build:
            context: .
            dockerfile: Dockerfile
        develop:
          watch:
            - action: rebuild
              files:
                - ./**/*.go
                - ./go.mod
                - ./go.sum
    mysql-8.0:
        image: mysql:8.0.28
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "12345678"
            MYSQL_ROOT_HOST: "%"
